#!/bin/bash
# This file copies all of the files from my machine into the dot files folder

#Generic, useful variables
working_dir=$(pwd -P)
script_path="$BASH_SOURCE"

# If we were called by a symbolic link we need to get back to the git repo
if [ -h $script_path ]; then
  # echo "$script_path IS A SYMBOLIC LINK"; # debug
  script_path=$( readlink -f $script_path; )
# else
  # echo "NOT A LINK";
fi
parent_path=$( cd "$(dirname "${script_path}")" ; pwd -P )

# go to the project root
cd "$parent_path";
project_root=$(git rev-parse --show-toplevel || echo ".")
cd "$project_root"
# Now we're in the root of the dot_files git repo.

# using . instead of source to force full path requirement
. "$parent_path/catch_errors.sh"; # for nicer error handling


# Setup variables
dotfile_zshrc_backup_file="zshrc_backup_$(date +%Y%m%d-%H%M%S).zshrc"
dotfile_zsh_folder="$HOME/.config/zsh"

# Copy all the files. TODO: Make this easier/smarter?
# TODO: For all the copying make a SOURCE_DIR and DEST_DIR variable
# To make it easier to identify issues
# TODO: check if the system file is nwer than repo file
echo -ne "copying helix config from repo => system ";
catch cp ./.config/helix/config.toml ~/.config/helix/config.toml;

echo -ne "copying vimrc from repo => system ";
catch cp ./.vimrc ~/.vimrc;

echo -ne "copying tmux config from repo => system ";
catch cp ./.tmux.conf  ~/.tmux.conf   
echo "";
# Copy all the non-machine-specific zsh files

catch cp ~/.zshrc ~/$dotfile_zshrc_backup_file;
echo -ne "Backed up zshrc file to $dotfile_zshrc_backup_file "; # Backup the current zsh file!
catch cp ./template.zshrc ~/.zshrc # COMMENTED OUT DUE TO DANGER
# I want to add a prompt but this is just my first draft

if [ ! -d "$dotfile_zsh_folder" ]; then
  echo "Creating $dotfile_zsh_folder"
  mkdir -p "$dotfile_zsh_folder"
fi

echo "Copying ZSH configs into $dotfile_zsh_folder"
# TODO: check if the system file is nwer than repo file
cp ./.config/zsh/base.zsh  "$dotfile_zsh_folder/base.zsh"
cp ./.config/zsh/development.zsh "$dotfile_zsh_folder/development.zsh"
cp ./.config/zsh/remote.zsh "$dotfile_zsh_folder/remote.zsh"

# ! ONLY copy this if we don't have one already. Can be per-machine!
dotfile_zsh_plugin_file="$dotfile_zsh_folder/plugins.zsh"
if [ -f "$dotfile_zsh_plugin_file" ]; then
  echo "NOT copying plugins file in case system has customizations at $dotfile_zsh_plugin_file";
else
  cp ./.config/zsh/plugins.zsh "$dotfile_zsh_plugin_file" # This is also per machine
fi
cp ./.config/zsh/work.zsh "$dotfile_zsh_folder/work.zsh"

# Make sure we go back and inform user it's all done
cd "$working_dir"
echo -e "CWD is back to $(pwd)\n\n✅ DONE dot_files backup"
